### ISSUE TITLE
More a question than an issue

### ISSUE THREAD

**Issue by BerserkJJ** [alt3/rank-my-wallet#208]
Hello,
Do you guys know how much time does it get for the website to get updated. For example, i created a new wallet for more than a week and when i launch a search, the wallet is still labelled as "ghost" with 0 erg.
Thanks in advance for any response !

**Comment by bravo-kernel** [comment]
Data is provided by the [Ergo Watch](https://ergo.watch/) API and should show the exact same balance as on the blockchain (realtime).

1. Do you see the expected (non-zero) blockchain balance when pasting your wallet address in e.g. https://ergoscan.io?
2. Could you be using a wrong box address? See this explanation about Ergo boxes on the [RankMyWallet FAQ page](https://rankmywallet.com/faq)

**Comment by BerserkJJ** [comment]
Hey, thanks for the fast response.
Yes, i do see the correct balance on ergoscan.
I tried to send everything on a new adress i generated but the problem remains the same
(for more context i also have an old wallet, and when i enter the adress, i have an amount that is an old amount, this is why i was thinking to an update that have to be done, maybe the website make some screenshot every x time..)
Weird, can't explain why

**Comment by bravo-kernel** [comment]
Thank you for the additional feedback. I have asked for a sanity check in the [Ergo Watch Discord](https://discord.com/channels/668903786361651200/896711052736233482).

**Comment by bravo-kernel** [comment]
Thank you for reporting, there was indeed an issue with the database which should now be fixed.

To see the reason, visit the Discord channel link I pasted above.

**Comment by BerserkJJ** [comment]
Yes , i followed the discussions on Discord and it is now working fine !
Thank you for the follow-up !
